#!/usr/bin/env bash
# Installs Nginx with the following configurations:

sudo apt update
sudo apt install nginx

# Copy the nginx configuration file from web-01
scp 209268@web-01:/etc/nginx/nginx.conf /etc/nginx/

# Update the hostname in the nginx configuration file
sudo sed -i "s/03-web-01/$HOSTNAME/g" /etc/nginx/nginx.conf

# Restart nginx
sudo service nginx restart

# Add the custom HTTP response header
sudo echo "add_header X-Served-By $HOSTNAME;" >> /etc/nginx/nginx.conf

# Restart nginx
sudo service nginx restart

