#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get install -y nginx

# create index.html file served out by server:
# & configure the redirection and return error pages
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

# configure Nginx
# and with custom response header configuration:
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;

     location     /redirect_me {
          return  301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }

     error_page    404 /404.html;
     location    /404 {
          root    /var/www/html;
     internal;
     }

     add_header X-Served-By \$hostname;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
